### ISSUE TITLE
memory access out of bounds

### ISSUE THREAD

**Issue by Molfith** [libpag/pag-web#1]
libpag.wasm:0x13e08a Uncaught (in promise) RuntimeError: memory access out of bounds
    at libpag.wasm:0x13e08a
    at ret.<computed> (libpag.js:3539:33)
    at Object.doRewind (libpag.js:3585:14)
    at libpag.js:3609:45

**Comment by zenoslin** [comment]
You can offer the bad case to the [libpag](https://github.com/Tencent/libpag) repository.
