### ISSUE TITLE
CompileError: WebAssembly.instantiate():

### ISSUE THREAD

**Issue by MyButifullyLife** [libpag/pag-web#3]
chrome 运行vue2 demo时报以下错误

libpag.umd.js?4b2e:2358 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (libpag.umd.js?4b2e:2358:1)
    at eval (libpag.umd.js?4b2e:2423:1)

![image](https://user-images.githubusercontent.com/16436933/166658364-d7721bbf-776f-4653-9e53-e9098d6d747a.png)

**Comment by zenoslin** [comment]
参考 [vue.config.js](https://github.com/libpag/pag-web/blob/main/vue/vue2/vue.config.js) 配置Webpack解决。
